// <auto-generated />
using BasketballTracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasketballTracking.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190726190658_SeedMigration")]
    partial class SeedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasketballTracking.Models.Conference", b =>
                {
                    b.Property<int>("ConferenceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.HasKey("ConferenceId");

                    b.ToTable("Conferences");

                    b.HasData(
                        new { ConferenceId = 1, ImageURL = "https://vignette.wikia.nocookie.net/prosportsteams/images/f/ff/Eastern_Conference_%28NBA%29.gif/revision/latest?cb=20120914185141", Name = "Eastern Conference" },
                        new { ConferenceId = 2, ImageURL = "https://vignette.wikia.nocookie.net/prosportsteams/images/1/10/Western_Conference_%28NBA%29.gif/revision/latest?cb=20120914191716", Name = "Western Conference" }
                    );
                });

            modelBuilder.Entity("BasketballTracking.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new { PlayerId = 1, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/2544.png", Name = "LeBron James", TeamId = 4 },
                        new { PlayerId = 2, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201939.png", Name = "Stephen Curry", TeamId = 5 },
                        new { PlayerId = 3, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202689.png", Name = "Kemba Walker", TeamId = 3 },
                        new { PlayerId = 4, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203507.png", Name = "Giannis Antetokounmpo", TeamId = 2 },
                        new { PlayerId = 5, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201567.png", Name = "Kevin Love", TeamId = 1 },
                        new { PlayerId = 6, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628398.png", Name = "Kyle Kuzma", TeamId = 4 },
                        new { PlayerId = 7, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202326.png", Name = "DeMarcus Cousins", TeamId = 4 },
                        new { PlayerId = 8, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203076.png", Name = "Anthony Davis", TeamId = 4 },
                        new { PlayerId = 9, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203114.png", Name = "Khris Middleton", TeamId = 2 },
                        new { PlayerId = 10, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202339.png", Name = "Eric Bledsoe", TeamId = 2 },
                        new { PlayerId = 11, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201572.png", Name = "Brook Lopez", TeamId = 2 },
                        new { PlayerId = 12, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1628369.png", Name = "Jayson Tatum", TeamId = 3 },
                        new { PlayerId = 13, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627759.png", Name = "Jaylen Brown", TeamId = 3 },
                        new { PlayerId = 14, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203935.png", Name = "Marcus Smart", TeamId = 3 },
                        new { PlayerId = 15, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629636.png", Name = "Darius Garland", TeamId = 1 },
                        new { PlayerId = 16, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1629012.png", Name = "Collin Sexton", TeamId = 1 },
                        new { PlayerId = 17, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626204.png", Name = "Larry Nance Jr.", TeamId = 1 },
                        new { PlayerId = 18, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1626156.png", Name = "D'Angelo Russel", TeamId = 5 },
                        new { PlayerId = 19, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202691.png", Name = "Klay Thompson", TeamId = 5 },
                        new { PlayerId = 20, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203110.png", Name = "Draymond Green", TeamId = 5 },
                        new { PlayerId = 21, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203081.png", Name = "Damien Lillard", TeamId = 6 },
                        new { PlayerId = 22, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203918.png", Name = "Rodney Hood", TeamId = 6 },
                        new { PlayerId = 23, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203994.png", Name = "Jusuf Nurkic", TeamId = 6 },
                        new { PlayerId = 24, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/203468.png", Name = "CJ McCollom", TeamId = 6 },
                        new { PlayerId = 25, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/200768.png", Name = "Kyle Lowry", TeamId = 7 },
                        new { PlayerId = 26, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201586.png", Name = "Serge Ibaka", TeamId = 7 },
                        new { PlayerId = 27, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201188.png", Name = "Marc Gasol", TeamId = 7 },
                        new { PlayerId = 28, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/1627832.png", Name = "Fred VanVleet", TeamId = 7 },
                        new { PlayerId = 29, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202331.png", Name = "Paul George", TeamId = 8 },
                        new { PlayerId = 30, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/202695.png", Name = "Kawhi Leonard", TeamId = 8 },
                        new { PlayerId = 31, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/101150.png", Name = "Lou Williams", TeamId = 8 },
                        new { PlayerId = 32, ImageURL = "https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/201976.png", Name = "Patrick Beverly", TeamId = 8 }
                    );
                });

            modelBuilder.Entity("BasketballTracking.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConferenceId");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("TeamId");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Teams");

                    b.HasData(
                        new { TeamId = 1, ConferenceId = 1, ImageURL = "https://stats.nba.com/media/img/teams/logos/CLE_logo.svg", Location = "Cleveland", Name = "Cavaliers" },
                        new { TeamId = 2, ConferenceId = 1, ImageURL = "https://stats.nba.com/media/img/teams/logos/MIL_logo.svg", Location = "Milwaukee", Name = "Bucks" },
                        new { TeamId = 3, ConferenceId = 1, ImageURL = "https://stats.nba.com/media/img/teams/logos/BOS_logo.svg", Location = "Boston", Name = "Celtics" },
                        new { TeamId = 4, ConferenceId = 2, ImageURL = "https://stats.nba.com/media/img/teams/logos/LAL_logo.svg", Location = "Los Angeles", Name = "Lakers" },
                        new { TeamId = 5, ConferenceId = 2, ImageURL = "https://stats.nba.com/media/img/teams/logos/GSW_logo.svg", Location = "Golden State", Name = "Warriors" },
                        new { TeamId = 6, ConferenceId = 2, ImageURL = "https://stats.nba.com/media/img/teams/logos/POR_logo.svg", Location = "Portland", Name = "Trail Blazers" },
                        new { TeamId = 7, ConferenceId = 1, ImageURL = "https://stats.nba.com/media/img/teams/logos/TOR_logo.svg", Location = "Toronto", Name = "Raptors" },
                        new { TeamId = 8, ConferenceId = 2, ImageURL = "https://stats.nba.com/media/img/teams/logos/LAC_logo.svg", Location = "Los Angeles", Name = "Clippers" }
                    );
                });

            modelBuilder.Entity("BasketballTracking.Models.Player", b =>
                {
                    b.HasOne("BasketballTracking.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BasketballTracking.Models.Team", b =>
                {
                    b.HasOne("BasketballTracking.Models.Conference")
                        .WithMany("Teams")
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
